# Generated by Django 2.1.1 on 2018-09-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180930_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
