# Generated by Django 2.1.1 on 2018-09-30 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180930_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='account_id',
            new_name='account',
        ),
    ]
